/**
 * Writes `src/lib/map/land.generated.ts` from `project.ts`. Run it with `pnpm map` after a node is
 * added to `src/lib/server/nodes.ts`; the map's test fails until it has been.
 */
import { writeFileSync } from 'node:fs';
import { build } from './project.ts';

const geometry = build();
const literal = (value: unknown) => JSON.stringify(value);

const source = `/**
 * Generated by scripts/land.ts: the projected land, graticule, nodes and mesh of the world map.
 * Do not edit; \`pnpm map\` writes it again.
 */
import type { Node } from '../server/nodes.ts';

export const WIDTH = ${geometry.width};
export const HEIGHT = ${geometry.height};

/** Equal Earth, as d3-geo's \`geoEqualEarth().scale().translate()\` takes it. */
export const PROJECTION = ${literal(geometry.projection)} as const;

export const LAND = ${literal(geometry.land)};

export const GRATICULE = ${literal(geometry.graticule)};

/** Each node's place on the plot. */
export const POINTS: Record<Node, readonly [number, number]> = ${literal(geometry.points)};

/** A great circle between each pair of nodes that do not share a city. */
export const ARCS: readonly { from: Node; to: Node; d: string }[] = ${literal(geometry.arcs)};
`;

const target = new URL('../src/lib/map/land.generated.ts', import.meta.url);
writeFileSync(target, source);
console.log(`${target.pathname}: ${(source.length / 1024).toFixed(1)} KiB`);
