/**
 * Writes `src/lib/map/land.generated.ts` from `project.ts`. Run it with `pnpm map` after a node is
 * added to `src/lib/server/nodes.ts`; the map's test fails until it has been.
 */
import { writeFileSync } from 'node:fs';
import { build, DOT, PITCH } from './project.ts';

const geometry = build();
const literal = (value: unknown) => JSON.stringify(value);

const source = `/**
 * Generated by scripts/land.ts: the land as dots, the nodes and the mesh of the world map.
 * Do not edit; \`pnpm map\` writes it again.
 */
import type { Node } from '../server/nodes.ts';

export const WIDTH = ${geometry.width};
export const HEIGHT = ${geometry.height};

/** Mercator, as d3-geo's \`geoMercator().scale().translate()\` takes it. */
export const PROJECTION = ${literal(geometry.projection)} as const;

/** A dot's side and the pitch between dots: \`DOTS\` is stroked this wide and dashed this way. */
export const DOT = ${DOT};
export const PITCH = ${PITCH};

/** A run of land cells per row, each a line through the middle of its dots. */
export const DOTS = ${literal(geometry.dots)};

/** Each node's latitude and longitude, as nodes.ts has it, for the globe. */
export const LOCATIONS: Record<Node, readonly [number, number]> = ${literal(geometry.locations)};

/** Each node's place on the plot. */
export const POINTS: Record<Node, readonly [number, number]> = ${literal(geometry.points)};
`;

const target = new URL('../src/lib/map/land.generated.ts', import.meta.url);
writeFileSync(target, source);
console.log(`${target.pathname}: ${(source.length / 1024).toFixed(1)} KiB`);
