// @generated from every apps/*/service.toml by `mise run scopes`; do not edit.
import type { Scope } from './table.ts';

export const SCOPES: Readonly<Record<string, Scope>> = {
	aka: {
		placement: 'workers',
		binding: 'AKA',
		worker: 'aka',
		routes: [
			{
				path: '/*',
				cors: {
					origins: 'public',
					methods: ['GET', 'HEAD'],
					headers: [],
				},
				cache: {
					fulfilled: 300,
					accepted: 0,
					redirected: 300,
					rejected: 300,
					faulted: 0,
				},
				crawlable: true,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
	cdn: {
		placement: 'workers',
		binding: 'CDN',
		worker: 'cdn',
		routes: [
			{
				path: '/derive/*',
				cors: {
					origins: 'public',
					methods: ['GET', 'HEAD'],
					headers: [],
				},
				cache: {
					fulfilled: 'immutable',
					accepted: 0,
					redirected: 'immutable',
					rejected: 300,
					faulted: 0,
				},
				crawlable: true,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
			{
				path: '/object/*',
				cors: {
					origins: 'public',
					methods: ['GET', 'HEAD'],
					headers: [],
				},
				cache: {
					fulfilled: 'immutable',
					accepted: 0,
					redirected: 'immutable',
					rejected: 300,
					faulted: 0,
				},
				crawlable: true,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
			{
				path: '/*',
				cors: {
					origins: 'public',
					methods: ['GET', 'HEAD'],
					headers: [],
				},
				cache: {
					fulfilled: 3600,
					accepted: 0,
					redirected: 3600,
					rejected: 300,
					faulted: 0,
				},
				crawlable: true,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
	geo: {
		placement: 'home',
		binding: 'HOME',
		limits: [
			{
				methods: ['GET', 'HEAD'],
				path: '/address',
				count: 60,
				seconds: 60,
			},
			{
				methods: ['GET', 'HEAD'],
				path: '/ip',
				count: 60,
				seconds: 60,
			},
		],
		routes: [
			{
				path: '/*',
				cors: {
					origins: 'public',
					methods: ['GET', 'HEAD'],
					headers: [],
				},
				cache: {
					fulfilled: 86400,
					accepted: 0,
					redirected: 900,
					rejected: 300,
					faulted: 300,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
	hook: {
		placement: 'workers',
		binding: 'HOOK',
		worker: 'hook',
		routes: [
			{
				path: '/*',
				cache: {
					fulfilled: 900,
					accepted: 0,
					redirected: 900,
					rejected: 300,
					faulted: 300,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
	probe: {
		placement: 'home',
		binding: 'HOME',
		limits: [
			{
				methods: ['GET', 'HEAD'],
				path: '/checks',
				count: 60,
				seconds: 60,
			},
			{
				methods: ['GET', 'HEAD'],
				path: '/checks/*',
				count: 30,
				seconds: 60,
			},
		],
		routes: [
			{
				path: '/*',
				cache: {
					fulfilled: 60,
					accepted: 0,
					redirected: 900,
					rejected: 300,
					faulted: 30,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
	shot: {
		placement: 'home',
		binding: 'HOME',
		limits: [
			{
				methods: ['POST'],
				path: '/tasks',
				count: 3,
				seconds: 60,
			},
		],
		routes: [
			{
				path: '/pictures/*',
				cache: {
					fulfilled: 900,
					accepted: 0,
					redirected: 0,
					rejected: 0,
					faulted: 0,
				},
				crawlable: false,
				exposed: true,
				forbidden: ['internal', 'fresh'],
				auth: 'none',
			},
			{
				path: '/tasks/*',
				cache: {
					fulfilled: 300,
					accepted: 0,
					redirected: 0,
					rejected: 0,
					faulted: 0,
				},
				crawlable: false,
				exposed: true,
				forbidden: ['internal', 'fresh'],
				auth: 'none',
			},
			{
				path: '/*',
				cache: {
					fulfilled: 0,
					accepted: 0,
					redirected: 0,
					rejected: 0,
					faulted: 0,
				},
				crawlable: false,
				exposed: true,
				forbidden: ['internal', 'fresh'],
				auth: 'none',
			},
		],
	},
	site: {
		placement: 'workers',
		binding: 'SITE',
		worker: 'site',
		prefix: '/api',
		routes: [
			{
				path: '/like',
				cache: {
					fulfilled: 0,
					accepted: 0,
					redirected: 300,
					rejected: 0,
					faulted: 0,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
			{
				path: '/*',
				cache: {
					fulfilled: 300,
					accepted: 0,
					redirected: 300,
					rejected: 300,
					faulted: 0,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
	telemetry: {
		placement: 'home',
		binding: 'HOME',
		limits: [
			{
				methods: ['GET', 'HEAD'],
				path: '/machine',
				count: 120,
				seconds: 60,
			},
			{
				methods: ['GET', 'HEAD'],
				path: '/machine/series',
				count: 120,
				seconds: 60,
			},
			{
				methods: ['GET', 'HEAD'],
				path: '/services',
				count: 120,
				seconds: 60,
			},
			{
				methods: ['GET', 'HEAD'],
				path: '/topology',
				count: 120,
				seconds: 60,
			},
			{
				methods: ['GET', 'HEAD'],
				path: '/activity',
				count: 120,
				seconds: 60,
			},
		],
		routes: [
			{
				path: '/services',
				cache: {
					fulfilled: 5,
					accepted: 0,
					redirected: 900,
					rejected: 300,
					faulted: 30,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
			{
				path: '/machine',
				cache: {
					fulfilled: 5,
					accepted: 0,
					redirected: 900,
					rejected: 300,
					faulted: 30,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
			{
				path: '/*',
				cache: {
					fulfilled: 60,
					accepted: 0,
					redirected: 900,
					rejected: 300,
					faulted: 30,
				},
				crawlable: false,
				exposed: true,
				forbidden: [],
				auth: 'none',
			},
		],
	},
};
